### ISSUE TITLE
support for php 8.2 & 8.3

### ISSUE THREAD

**Issue by tysonchamp** [dedi74132/phpbolt#2]

**Comment by ZeridosIT** [comment]
Download link: https://phpbolt.com/wp-content/uploads/2024/03/phpBolt-extension-1.0.5.zip

Source: https://www.aapanel.com/forum/d/18167-php-bolt-dont-install/5

Hope to help someone :)

**Comment by winds1983** [comment]
@ZeridosIT I need it and this helped me, thanks.
